name: check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  package-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check repository package
        run: scripts/check-repo.sh
